# Generated by Django 3.2.3 on 2021-07-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0019_fatores_planejamento'),
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider_elemento', models.BooleanField(default=False)),
                ('lider_objetivo', models.BooleanField(default=False)),
                ('elemento', models.ManyToManyField(blank=True, null=True, to='swot.Elementos')),
                ('planejamento', models.ManyToManyField(blank=True, null=True, related_name='plan_rel', to='swot.Planejamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
