# Generated by Django 3.2.3 on 2021-07-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0019_fatores_planejamento'),
        ('users', '0003_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='lider_elemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider_elem_rel', to='swot.elementos'),
        ),
    ]
