# Generated by Django 3.2.3 on 2021-07-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0020_auto_20210723_0649'),
        ('users', '0004_alter_membro_lider_elemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='membro',
            name='lider_objetivo',
        ),
        migrations.AddField(
            model_name='membro',
            name='lider_objetivo',
            field=models.ManyToManyField(blank=True, null=True, related_name='obj_rel', to='swot.Objetivo'),
        ),
    ]
