# Generated by Django 3.2.3 on 2021-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210724_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='git',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
