# Generated by Django 3.2.3 on 2021-07-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210724_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='membro',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_pics'),
        ),
    ]
