# Generated by Django 3.2.3 on 2021-07-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0020_auto_20210723_0649'),
        ('users', '0007_auto_20210724_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='lider_elemento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider_elem_rel', to='swot.elementos'),
        ),
    ]
