# Generated by Django 3.2.3 on 2021-07-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_membro_lider_elemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
