# Generated by Django 3.2.3 on 2021-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0021_auto_20210729_1136'),
        ('users', '0010_remove_membro_lider_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='lider_objetivo',
            field=models.ManyToManyField(blank=True, null=True, related_name='objetivo_rel', to='swot.Objetivo'),
        ),
    ]
