# Generated by Django 3.2.3 on 2021-08-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_membro_lider_objetivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='elemento',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='lider_elemento',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='lider_objetivo',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='planejamento',
        ),
    ]
