# Generated by Django 3.2.3 on 2021-09-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0023_auto_20210730_0953'),
        ('users', '0013_auto_20210826_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidado', to='users.membro')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='users.membro')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swot.planejamento')),
            ],
        ),
    ]
