# Generated by Django 3.2.3 on 2021-09-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
