# Generated by Django 3.2.3 on 2021-09-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_convite_resolvido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='primeiro_nome',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='ultimo_nome',
        ),
    ]
