# Generated by Django 3.2.3 on 2021-09-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210914_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
