# Generated by Django 3.2.3 on 2021-07-07 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swot', '0002_alter_projeto_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
