# Generated by Django 3.2.3 on 2021-07-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0008_elementos_planejamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
