# Generated by Django 3.2.3 on 2021-07-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0009_planejamento_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='fator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swot.fatores'),
        ),
    ]
