# Generated by Django 3.2.3 on 2021-07-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0010_objetivo_fator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatores',
            old_name='tipo',
            new_name='elemento',
        ),
    ]
