# Generated by Django 3.2.3 on 2021-07-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0012_planejamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
