# Generated by Django 3.2.3 on 2021-07-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0014_auto_20210716_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
