# Generated by Django 3.2.3 on 2021-07-21 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swot', '0016_auto_20210719_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider_elemento', models.BooleanField(default=False)),
                ('lider_objetivo', models.BooleanField(default=False)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swot.elementos')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swot.planejamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Swot',
        ),
    ]
