# Generated by Django 3.2.3 on 2021-07-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0017_auto_20210721_0513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membro',
        ),
    ]
