# Generated by Django 3.2.3 on 2021-07-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0018_delete_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatores',
            name='planejamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swot.planejamento'),
        ),
    ]
