# Generated by Django 3.2.3 on 2021-07-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swot', '0019_fatores_planejamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='membros',
            field=models.ManyToManyField(blank=True, null=True, related_name='membros_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
