# Generated by Django 3.2.3 on 2021-07-29 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_membro_lider_objetivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swot', '0020_auto_20210723_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='elementos_membros_rel', to='users.Membro'),
        ),
        migrations.AlterField(
            model_name='elementos',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.membro'),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_lider_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='membros',
            field=models.ManyToManyField(blank=True, null=True, related_name='plan_membros_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
