# Generated by Django 3.2.3 on 2021-10-08 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_membro_nome'),
        ('swot', '0023_auto_20210730_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.membro')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swot.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioFator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swot.fatores')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.membro')),
            ],
        ),
    ]
