# Generated by Django 3.2.3 on 2021-11-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0027_comentarioobjetivo_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamento',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='planejamento',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
